# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_image', models.ImageField(blank=True, upload_to='')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.TextField()),
                ('image_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
    ]
