# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='actual_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
