# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-09 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200809_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_name',
            new_name='name',
        ),
    ]
